// 公開用の日本語原稿。本人のプロフィールと開発実績に基づく。
export const content = {
  nav: { about: "自己紹介", skills: "スキル", projects: "制作物", experience: "経歴", contact: "お問い合わせ" },
  hero: {
    greeting: "ヘイン テッ アウン",
    name: "Hein Htet Aung",
    role: "フルスタック開発者",
    tagline: "現場の困りごとを見つけ、使う人と一緒に改善する。独学で学んだWeb開発を生かし、職場で使われる業務アプリや、東京でスポーツ仲間を探すサービスを個人で開発しています。",
    ctaPrimary: "制作物を見る",
    ctaSecondary: "お問い合わせ",
    status: "2027年3月卒業予定・新卒エンジニア職を志望",
    stats: [
      { label: "業務アプリを利用する同僚", value: "7名" },
      { label: "約2時間かかっていた集計", value: "10〜20分" },
      { label: "日本語能力試験", value: "N1" },
      { label: "TOEIC L&R", value: "830点" },
    ],
  },
  about: {
    title: "自己紹介",
    heading: "課題の発見から、開発・運用・改善まで",
    body: [
      "ミャンマー出身、東京在住のヘイン テッ アウンです。開智国際大学 国際教養学部に在籍し、2027年3月に卒業予定です。アルバイトと両立しながら独学でWeb開発を学び、画面の実装からデータベース設計、デプロイ、運用まで取り組んできました。",
      "スギ薬局のアルバイトでは、紙と電卓で行っていた販売実績・ポイント集計に課題を感じ、業務アプリを開発しました。自分用から始めた仕組みを同僚7名が使う形へ広げ、利用者の声をもとにオフライン対応などの改善を続けています。",
      "大切にしているのは、機能を作ることだけでなく、使う人の課題が解決できたかを確かめることです。今後はバックエンドやソフトウェア設計の理解を深め、AIにも学びを広げながら、チームでプロダクトを育てられるエンジニアを目指しています。",
    ],
    highlights: [
      { icon: "GraduationCap", text: "開智国際大学 国際教養学部・2027年3月卒業予定" },
      { icon: "MapPin", text: "東京在住・ミャンマー出身" },
      { icon: "Languages", text: "日本語：JLPT N1／英語：TOEIC 830点／ミャンマー語：母語" },
      { icon: "Heart", text: "関心分野：バックエンド・AI・プロダクト開発" },
    ],
  },
  skills: {
    title: "スキル",
    subtitle: "個人開発と、実際の利用者がいるアプリの運用で使ってきた技術です。",
    groups: [
      { name: "フロントエンド", color: "from-cyan-500 to-blue-500", items: ["Next.js", "React", "TypeScript", "JavaScript", "Tailwind CSS"] },
      { name: "バックエンド・データベース", color: "from-emerald-500 to-teal-500", items: ["PHP", "Laravel", "PostgreSQL", "MySQL", "Supabase", "Eloquent ORM", "REST API設計"] },
      { name: "オフライン対応・データ整合性", color: "from-violet-500 to-purple-500", items: ["PWA", "IndexedDB", "オフライン同期", "冪等性キー", "認証・権限管理"] },
      { name: "テスト・デプロイ", color: "from-pink-500 to-rose-500", items: ["Vitest", "VPS", "Vercel", "不具合の再現・修正", "利用者による動作確認"] },
      { name: "プロダクト開発", color: "from-amber-500 to-orange-500", items: ["現場の課題発見", "要件整理", "データベース設計", "利用者の声をもとに改善", "日英対応の画面設計"] },
    ],
  },
  projects: {
    title: "制作物",
    subtitle: "業務で利用されているアプリから学習用のシステムまで。課題と、解決のために選んだ技術を紹介します。",
    items: [
      {
        slug: "sugi-sale-app",
        title: "Sugi Sale App",
        period: "個人開発・アルバイト先で運用中",
        tagline: "紙と電卓の集計をWebアプリへ。約2時間の作業を10〜20分に。",
        description: "販売実績とポイントを紙に記録し、電卓で集計する作業の手間を減らすために開発しました。商品を選ぶだけで記録とポイント計算ができ、現在は同僚7名が利用しています。自分用のツールから始め、利用者のフィードバックを受けて認証・権限管理やオフライン同期を追加しました。",
        tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PostgreSQL", "PWA", "IndexedDB", "Vitest", "VPS"],
        features: ["商品選択による販売実績の記録・ポイント計算", "複数の利用者に対応する認証・権限管理", "IndexedDBで通信が不安定な環境でも入力を継続", "通信復帰後にローカルデータを同期", "冪等性キーで再送時の重複登録を防止", "利用者の声をもとに操作性と運用を改善"],
        live: null,
        repo: "https://github.com/heinaungtesting/sugi-sale-app",
        status: "実務で利用中・同僚7名",
        accent: "emerald",
      },
      {
        slug: "sportsmatch",
        title: "SportsMatch Tokyo",
        period: "2026年3月〜・個人開発",
        tagline: "東京でスポーツをしたい人と、参加できる場をつなぐ。",
        description: "スポーツ仲間や参加できるコミュニティを探す手間と、言語の壁を減らすために開発したWebサービスです。スポーツ・日時・場所からセッションを探し、参加や新規作成ができます。日本語と英語に対応し、初めて使う人にも分かりやすい操作を目指して改善しています。",
        tech: ["Next.js", "React", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS", "Vercel"],
        features: ["ユーザー認証", "セッションの一覧・詳細表示", "スポーツや日付による絞り込み", "セッションの作成・参加", "日本語・英語に対応した画面", "レスポンシブ対応と操作性の改善"],
        live: "https://sportsmatch-tokyo.vercel.app",
        repo: "https://github.com/heinaungtesting/webresevation",
        status: "品質・操作性を改善中",
        accent: "cyan",
      },
      {
        slug: "pos",
        title: "POS / EC 管理システム",
        period: "個人開発・学習用",
        tagline: "商品・カート・注文をつなぎ、バックエンド設計を学ぶ。",
        description: "Laravelで開発した、店舗・EC向けの商品・注文管理システムです。チュートリアルをなぞるだけでなく、複数の機能が連動するアプリを作ることで、MVC、認証・認可、データベースのリレーション、ORMを実践的に学びました。管理者と一般ユーザーの役割を分け、一連の購入・管理フローを実装しています。",
        tech: ["PHP", "Laravel", "MySQL", "Eloquent ORM", "Blade", "Tailwind CSS", "Bootstrap", "JavaScript", "jQuery", "Breeze", "Sanctum", "Vite"],
        features: ["管理者・一般ユーザーの権限分離", "商品・カテゴリーの管理", "商品検索・絞り込み・カート", "購入・注文履歴・決済情報の管理", "評価・コメント・お問い合わせ", "プロフィール管理"],
        live: null,
        repo: "https://github.com/heinaungtesting/pos",
        status: "学習用プロジェクト",
        accent: "violet",
      },
    ],
  },
  experience: {
    title: "経歴",
    subtitle: "大学での学び、アルバイト、個人開発を両立しています。",
    items: [
      { period: "2023年4月〜2027年3月 卒業予定", role: "開智国際大学 国際教養学部", location: "在学中", bullets: ["国際教養学科に在籍", "在学中に独学でWeb開発を学び、個人プロジェクトに取り組む"] },
      { period: "2023年6月〜2024年6月", role: "バーガーキング", location: "アルバイト", bullets: ["学業と両立しながら勤務"] },
      { period: "2024年6月〜2025年6月", role: "ラーメン店", location: "アルバイト", bullets: ["飲食店でのアルバイトを継続"] },
      { period: "2025年6月〜現在", role: "スギ薬局", location: "東京・浅草／アルバイト", bullets: ["外国人のお客様も多い店舗で、レジ・接客業務を担当", "販売実績・ポイント集計の課題を見つけ、業務アプリを個人開発", "同僚7名が利用する仕組みへ広げ、フィードバックをもとに改善"] },
      { period: "2026年3月〜", role: "SportsMatch Tokyo", location: "個人開発", bullets: ["スポーツ仲間を探すサービスを企画・開発", "認証、セッション検索・作成・参加、日英表示を実装", "不具合の修正と使いやすさの改善に取り組む"] },
    ],
  },
  contact: {
    title: "お問い合わせ",
    subtitle: "2027年新卒・Web／フルスタック／バックエンドエンジニア職を志望",
    blurb: "利用者の課題を理解し、チームで改善を重ねながらプロダクトを育てる仕事がしたいと考えています。採用や開発に関するお話がありましたら、お気軽にご連絡ください。",
    channels: [
      { label: "メール", value: "hhamaster199@gmail.com", href: "mailto:hhamaster199@gmail.com", icon: "Mail" },
      { label: "GitHub", value: "@heinaungtesting", href: "https://github.com/heinaungtesting", icon: "Github" },
    ],
  },
  footer: { built: "Next.js・Tailwind CSS・Framer Motionで制作。", rights: "© 2026 Hein Htet Aung" },
} as const;
