// 公開用の日本語原稿。本人のプロフィールと開発実績に基づく。
export const content = {
  nav: { about: "自己紹介", skills: "スキル", projects: "制作物", experience: "経歴", contact: "お問い合わせ" },
  hero: {
    greeting: "ヘイン テッ アウン",
    name: "Hein Htet Aung",
    role: "Webエンジニア志望（フルスタック開発）",
    tagline: "現場の困りごとを見つけ、使う人と一緒に改善する。独学で学んだWeb開発を生かし、職場で使われる業務アプリや、東京でスポーツ仲間を探すサービスを個人で開発しています。",
    ctaPrimary: "制作物を見る",
    ctaSecondary: "お問い合わせ",
    status: "2027年3月卒業予定・2027年4月入社可能",
    stats: [
      { label: "業務アプリを利用する同僚", value: "7名" },
      { label: "約2時間かかっていた集計", value: "10〜20分" },
      { label: "日本語能力試験", value: "N1" },
      { label: "TOEIC L&R", value: "830点" },
    ],
  },
  about: {
    title: "自己紹介",
    heading: "課題の発見から、開発・運用・改善まで",
    body: [
      "ミャンマー出身、東京在住のヘイン テッ アウンです。開智国際大学 国際教養学部に在籍し、2027年3月に卒業予定です。アルバイトと両立しながら独学でWeb開発を学び、画面の実装からデータベース設計、デプロイ、運用まで取り組んできました。",
      "スギ薬局のアルバイトでは、紙と電卓で行っていた販売実績・ポイント集計に課題を感じ、業務アプリを開発しました。自分用から始めた仕組みを同僚7名が使う形へ広げ、利用者の声をもとにオフライン対応などの改善を続けています。",
      "大切にしているのは、機能を作ることだけでなく、使う人の課題が解決できたかを確かめることです。今後はバックエンドやソフトウェア設計の理解を深め、AIにも学びを広げながら、チームでプロダクトを育てられるエンジニアを目指しています。",
    ],
    strengthsTitle: "私の強み",
    strengths: [
      { title: "課題を見つけ、自分で形にする力", text: "紙と電卓で行っていた販売実績・ポイント集計に課題を感じ、業務アプリを自ら開発しました。約2時間かかっていた集計作業を10〜20分に短縮しています。" },
      { title: "使う人の声をもとに改善を続ける力", text: "自分用のツールから始め、同僚7名が使う形へ広げました。利用者のフィードバックを受けて、認証・権限管理やオフライン同期を追加してきました。" },
      { title: "多言語でのコミュニケーション力", text: "日本語（JLPT N1）、英語（TOEIC 830点）、ミャンマー語（母語）を使えます。外国人のお客様も多い店舗での接客や、日英対応のサービス開発に生かしています。" },
    ],
    highlights: [
      { icon: "GraduationCap", text: "開智国際大学 国際教養学部・2027年3月卒業予定" },
      { icon: "MapPin", text: "東京在住・ミャンマー出身" },
      { icon: "Languages", text: "日本語：JLPT N1（2025年12月）／英語：TOEIC L&R 830点（2024年1月）／ミャンマー語：母語" },
      { icon: "BookOpen", text: "注力科目：ウェブプログラミング演習Ⅱ（JavaScript・PHP・Python）" },
      { icon: "Heart", text: "関心分野：バックエンド・AI・プロダクト開発" },
      { icon: "Trophy", text: "趣味・特技：卓球／バドミントン（ミャンマーの地方大会で優勝）" },
    ],
    careerTitle: "日本でのキャリアについて",
    career: "大学卒業後も日本で長期的にキャリアを築きたいと考えています。特にIT・Webエンジニアとして、技術力だけでなく、日本語・英語を生かしながら多様なメンバーと協働し、プロダクト開発に長期的に貢献していきたいです。",
  },
  skills: {
    title: "スキル",
    subtitle: "個人開発と、実際の利用者がいるアプリの運用で使ってきた技術です。",
    groups: [
      { name: "フロントエンド", color: "from-cyan-500 to-blue-500", items: ["Next.js", "React", "TypeScript", "JavaScript", "Tailwind CSS"] },
      { name: "バックエンド・データベース", color: "from-emerald-500 to-teal-500", items: ["PHP", "Laravel", "PostgreSQL", "MySQL", "Supabase", "Eloquent ORM", "REST API設計"] },
      { name: "オフライン対応・データ整合性", color: "from-violet-500 to-purple-500", items: ["PWA", "IndexedDB", "オフライン同期", "冪等性キー", "認証・権限管理"] },
      { name: "テスト・デプロイ", color: "from-pink-500 to-rose-500", items: ["Vitest", "VPS", "Vercel", "不具合の再現・修正", "利用者による動作確認"] },
      { name: "プロダクト開発", color: "from-amber-500 to-orange-500", items: ["現場の課題発見", "要件整理", "データベース設計", "利用者の声をもとに改善", "日英対応の画面設計"] },
    ],
  },
  projects: {
    title: "制作物",
    subtitle: "業務で利用されているアプリから学習用のシステムまで。課題と、解決のために選んだ技術を紹介します。",
    items: [
      {
        slug: "sugi-sale-app",
        title: "Sugi Sale App",
        period: "個人開発・アルバイト先で運用中",
        tagline: "紙と電卓の集計をWebアプリへ。約2時間の作業を10〜20分に。",
        background: "現場では販売実績とポイントを紙に記録し、最後に電卓で集計していました。時間がかかるだけでなく計算ミスも起こりやすかったため、「毎日の作業をもっと簡単にできないか」と考えたことがきっかけです。",
        future: "利用者のフィードバックを継続して集め、入力操作をさらに減らしたいと考えています。データのバックアップや監視を強化し、蓄積したデータの可視化で販売状況の改善にもつながる仕組みへ育てます。",
        description: "販売実績とポイントを紙に記録し、電卓で集計する作業の手間と計算ミスを減らすために開発しました。商品を選ぶだけで記録とポイント計算ができ、現在は同僚7名が利用しています。自分用のツールから始め、利用者のフィードバックを受けて認証・権限管理やオフライン同期を追加しました。",
        tech: ["Next.js", "React", "TypeScript", "Tailwind CSS", "PostgreSQL", "PWA", "IndexedDB", "Vitest", "VPS"],
        features: ["商品選択による販売実績の記録・ポイント計算", "複数の利用者に対応する認証・権限管理", "IndexedDBで通信が不安定な環境でも入力を継続", "通信復帰後にローカルデータを同期", "冪等性キーで再送時の重複登録を防止", "利用者の声をもとに操作性と運用を改善"],
        live: null,
        repo: "https://github.com/heinaungtesting/sugi-sale-app",
        status: "実務で利用中・同僚7名",
        accent: "emerald",
      },
      {
        slug: "sportsmatch",
        title: "SportsMatch Tokyo",
        period: "2026年3月〜・個人開発",
        tagline: "東京でスポーツをしたい人と、参加できる場をつなぐ。",
        background: "東京でスポーツをしたくても、開催日時や場所が固定されていたり、参加できるコミュニティを探すのに手間がかかったりします。外国人には言語の壁もあるため、日本人と外国人のどちらも参加しやすいサービスを作ろうと考えました。",
        future: "まずは主要な不具合を減らし、初めての人でも迷わず使える状態にします。その後、DiscordやSNS、スポーツ関連コミュニティで紹介して利用者の声を集め、検索や参加までの導線を改善していきます。",
        description: "スポーツ仲間や参加できるコミュニティを探す手間と、言語の壁を減らすために開発したWebサービスです。スポーツ・日時・場所からセッションを探し、参加や新規作成ができます。日本語と英語に対応し、初めて使う人にも分かりやすい操作を目指して改善しています。",
        tech: ["Next.js", "React", "TypeScript", "Supabase", "PostgreSQL", "Tailwind CSS", "Vercel"],
        features: ["ユーザー認証", "セッションの一覧・詳細表示", "スポーツや日付による絞り込み", "セッションの作成・参加", "日本語・英語に対応した画面", "レスポンシブ対応と操作性の改善"],
        live: "https://sportsmatch-tokyo.vercel.app",
        repo: "https://github.com/heinaungtesting/webresevation",
        status: "公開前の品質改善フェーズ",
        accent: "cyan",
      },
      {
        slug: "pos",
        title: "POS / EC 管理システム",
        period: "個人開発・学習用",
        tagline: "商品・カート・注文をつなぎ、バックエンド設計を学ぶ。",
        background: "チュートリアルをなぞるだけでなく、複数の機能が連動するアプリを自分で作り、MVC、認証・認可、リレーショナルデータベース設計、ORMを体系的に理解したいと考えました。機能が増えるほど設計の一貫性や責務分離が重要になることを経験しました。",
        future: "在庫管理や売上分析など実店舗での利用を意識した機能を追加し、自動テスト・セキュリティ・パフォーマンスも改善して、保守しやすく安定したシステムにしていきます。",
        description: "Laravelで開発した、店舗・EC向けの商品・注文管理システムです。チュートリアルをなぞるだけでなく、複数の機能が連動するアプリを作ることで、MVC、認証・認可、データベースのリレーション、ORMを実践的に学びました。管理者と一般ユーザーの役割を分け、一連の購入・管理フローを実装しています。",
        tech: ["PHP", "Laravel", "MySQL", "Eloquent ORM", "Blade", "Tailwind CSS", "Bootstrap", "JavaScript", "jQuery", "Breeze", "Sanctum", "Vite"],
        features: ["管理者・一般ユーザーの権限分離", "商品・カテゴリーの管理", "商品検索・絞り込み・カート", "購入・注文履歴・決済情報の管理", "評価・コメント・お問い合わせ", "プロフィール管理"],
        live: null,
        repo: "https://github.com/heinaungtesting/pos",
        status: "学習用プロジェクト",
        accent: "violet",
      },
    ],
  },
  experience: {
    title: "経歴",
    subtitle: "大学での学び、アルバイト、個人開発を両立しています。",
    items: [
      { period: "2018年4月〜2020年4月", role: "ELC私立高等学校", location: "ミャンマー／卒業", bullets: ["ミャンマーの私立高等学校を卒業"] },
      { period: "2023年4月〜2027年3月 卒業見込み", role: "開智国際大学 国際教養学部 国際教養学科", location: "在学中", bullets: ["「ウェブプログラミング演習Ⅱ」でJavaScript・PHP・Pythonを用いたWebアプリ開発を学習", "サーバーサイド処理、データベース連携、システム設計、Webセキュリティを学ぶ", "授業と並行して独学でWeb開発を学び、個人プロジェクトに取り組む"] },
      { period: "2023年6月〜2024年6月", role: "バーガーキング", location: "アルバイト", bullets: ["接客、レジ対応、商品提供、店内業務を担当", "日本語を使用して幅広いお客様に対応", "混雑時にはスタッフと連携し、正確かつ迅速な商品提供を行った"] },
      { period: "2024年6月〜2025年6月", role: "ラーメン バリ男", location: "アルバイト", bullets: ["接客、注文対応、料理提供、片付けなどの店舗業務を担当", "日本語でお客様への案内・接客を行い、忙しい時間帯でも周囲と連携して店舗運営を支えた", "スピードと正確性を意識した業務遂行力を身につけた"] },
      { period: "2025年6月〜現在", role: "スギ薬局", location: "東京・浅草／アルバイト", bullets: ["外国人のお客様も多い店舗で、レジ・接客業務を担当", "販売実績・ポイント集計の課題を見つけ、業務アプリを個人開発", "同僚7名が利用する仕組みへ広げ、フィードバックをもとに改善"] },
      { period: "2026年3月〜現在", role: "SportsMatch Tokyo", location: "個人開発", bullets: ["スポーツ仲間を探すサービスを企画・開発", "認証、セッション検索・作成・参加、日英表示を実装", "不具合の修正と使いやすさの改善に取り組む"] },
    ],
  },
  contact: {
    title: "お問い合わせ",
    subtitle: "2027年新卒・Web／フルスタック／バックエンドエンジニア職を志望",
    blurb: "利用者の課題を理解し、チームで改善を重ねながらプロダクトを育てる仕事がしたいと考えています。2027年4月から入社可能です。採用や開発に関するお話がありましたら、お気軽にご連絡ください。",
    channels: [
      { label: "メール", value: "hhamaster199@gmail.com", href: "mailto:hhamaster199@gmail.com", icon: "Mail" },
      { label: "GitHub", value: "@heinaungtesting", href: "https://github.com/heinaungtesting", icon: "Github" },
    ],
  },
  footer: { built: "Next.js・Tailwind CSS・Framer Motionで制作。", rights: "© 2026 Hein Htet Aung" },
} as const;
